version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - pip
    groups:
      dev-dependencies:
        patterns:
          - ruff
          - mypy
          - pytest*
          - structlog
          - httpx
          - pydantic

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
