apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: socialpulse-data
  namespace: socialpulse
  labels:
    app.kubernetes.io/name: socialpulse
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
